backend/Event_Management/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
import notifications.urls
from django.conf.urls.static import static

urlpatterns = [
	path('forms/', include('forms.urls')),
	path('resources/', include('resources.urls')),
	path('pre_events/', include('pre_events.urls')),
	path('events/', include('events.urls')),
	path('users/', include('users.urls')),
	path('admin/', admin.site.urls),
	path('notificacoes/', include('notificacoes.urls')),
	path('', include('main.urls')),
    path('', include("notifications.urls", namespace='notifications')),

]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

backend/notificacoes/urls.py
from . import views
from django.urls import path
from django.urls import re_path as pattern
from main import urls

app_name = 'notificacoes'

urlpatterns = [


    path('detalhes/<int:id>', views.sem_notificacoes,
         name='sem-notificacoes'),
    path('detalhes/<int:id>/<int:nr>', views.categorias_notificacao_automatica,
         name='categorias-notificacao-automatica'),
    path('apagarnotificacao/<int:id>/<int:nr>', views.apagar_notificacao_automatica,
         name='apagar-notificacao-automatica'),

    path('limpar/<int:id>', views.limpar_notificacoes,
         name='limpar-notificacoes'),
    path('marcarcomolida', views.marcar_como_lida,
         name='ler-notificacoes'),
    #     path('notificar_teste/<str:sigla>/<int:id>', views.enviar_notificacao_automatica,
    #          name='notificar'),

#     ################################ Mensagens ###########################

#     path('escolhertipo', views.escolher_tipo, name="enviar-notificacao"),
#     path('criarmensagem/<int:id>', views.criar_mensagem, name="escrever-mensagem"),
#     path('criarmensagemuo/<int:id>',
#          views.criar_mensagem_uo, name="criar-mensagem-uo"),
#     path('criarmensagemadmin/<int:id>',
#          views.criar_mensagem_admin, name="criar-mensagem-admin"),
#     path('criarmensagemparticipante/<int:id>',
#          views.criar_mensagem_participante, name="criar-mensagem-participante"),
#     path('mensagens/<int:id>', views.sem_mensagens,
#          name='sem-mensagens'),
#     path('concluirenvio', views.concluir_envio,
#          name='concluir-envio'),
#     path('mensagens/<int:id>/<int:nr>', views.detalhes_mensagens,
#          name='detalhes-mensagem'),
#     path('apagarmensagem/<int:id>/<int:nr>', views.apagar_mensagem,
#          name='apagar-mensagem'),
#     path('limparmensganes/<int:id>', views.limpar_mensagens,
#          name='limpar-mensagens'),
#     path('marcarmensagemcomolida/<int:id>', views.mensagem_como_lida,
#          name='ler-mensagens'),
]

backend/notificacoes/models.py
from django.db import models
from django.utils import timezone
from notifications.base.models import AbstractNotification
from resources.models import *


class Notificacao(AbstractNotification):
    titulo = models.CharField(max_length=255)
    descricao = models.CharField(max_length=255)
    tipo = models.CharField(max_length=255)
    class Meta(AbstractNotification.Meta):
        abstract = False
        db_table = 'Notificacao'
        app_label = 'notificacoes'


# Coloca temporariamente notificações geradas automaticamente com conteúdo informativo, quando passam 5 dias a notificação é enviada 
# e é apagada desta tabela da base de dados
class InformacaoNotificacao(models.Model):
    id = models.AutoField( primary_key=True)
    data = models.DateTimeField(default=timezone.now, db_index=True)
    pendente = models.BooleanField(null=False)
    titulo 	= models.CharField(max_length=255)
    descricao = models.CharField( max_length=255)
    emissor = models.ForeignKey(Generaluser, models.CASCADE, related_name='envia',null=True)  
    recetor = models.ForeignKey(Generaluser, models.CASCADE, related_name='recebe',null=True,blank=True)  
    tipo = models.CharField( max_length=255)	
    lido = models.BooleanField( null=False)	
    class Meta:
        db_table = 'InformacaoNotificacao'

backend/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group
from django.core.validators import RegexValidator

from resources.models import Generaluser, Participant, Administrator, Proponent
groups = Group.objects.all()

signup_dict = {}

for group in groups:
	key = str(group.pk)
	value = str(group.name)
	signup_dict[key] = value

signup_choices = [(k, v) for k, v in signup_dict.items()]

class SignupForm(UserCreationForm):
	first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
	last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
	email = forms.EmailField(max_length=254, help_text='Required.')

	#	Regex magic for the contact field
	phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
	contact = forms.CharField(validators=[phone_regex], max_length=20, required=False)
	gabinete = forms.CharField(max_length=255, required=False, help_text='Optional.')

	user_field = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=signup_choices, label="Tipo de utilizador")

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'contact', 'gabinete', 'password1', 'password2', 'user_field')

class GeneralUserForm(forms.ModelForm):
	class Meta:
		model = Generaluser
		fields = {'user_ptr', 'contact'}

# class AuthUserGroupsForm(forms.ModelForm):
# 	class Meta:
# 		model = AuthUserGroups
# 		fields = {'user', 'group'}



class ParticipantForm(forms.ModelForm):
	class Meta:
		model = Participant
		fields = {'generaluser_ptr'}

class AdministratorForm(forms.ModelForm):
	class Meta:
		model = Administrator
		fields = {'generaluser_ptr', 'gabinete'}

class ProponentForm(forms.ModelForm):
	class Meta:
		model = Proponent
		fields = {'generaluser_ptr'}

backend/notificacoes/views.py
from django.http import HttpResponse
from .models import *
from resources.models import *
import math

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import *
from django.conf import settings
from django.contrib.auth.models import Group

from django.core.paginator import Paginator

from notifications.signals import notify
from django.utils import timezone

from datetime import datetime, timedelta

from .forms import *

from django.http import HttpResponseRedirect

from enum import Enum


def apagar_notificacao_automatica(request, id ,nr):
	''' Apagar uma notificação automática '''
	if request.user.is_authenticated:
		user = get_user(request)
	else:
		return redirect('utilizadores:mensagem', 5)
	try:    
		notificacao = Notificacao.objects.get(id=nr)
	except:
		return redirect("utilizadores:mensagem", 5)
	if notificacao == None:
		return redirect("utilizadores:mensagem", 5)
	notificacao.delete()

	page=request.GET.get('page')
	response = redirect('notificacoes:categorias-notificacao-automatica', id, 0)
	response['Location'] += '?page='+page
	return response


def limpar_notificacoes(request, id):
	''' Apagar notificacoes de um utilizadore por categorias '''
	if request.user.is_authenticated:
		user = get_user(request)
	else:
		return redirect('utilizadores:mensagem', 5)
	if id == 1:
		notificacoes = user.notifications.unread() 
	elif id ==2:
		notificacoes = user.notifications.read() 
	elif id == 3:
		notificacoes = Notificacao.objects.filter(recipient_id=user , public=False)
	elif id ==4:    
		notificacoes = Notificacao.objects.filter(recipient_id=user , public=True)
	elif id == 5:
		notificacoes = Notificacao.objects.filter(recipient_id=user , level="info")
	elif id ==6:  
		notificacoes = Notificacao.objects.filter(recipient_id=user , level="warning")
	elif id ==7: 
		notificacoes = Notificacao.objects.filter(recipient_id=user , level="error")
	elif id ==8:  
		notificacoes = Notificacao.objects.filter(recipient_id=user , level="success")
	else:
		notificacoes = user.notifications.all()
	for x in notificacoes:
		x.delete()

	return redirect('notificacoes:categorias-notificacao-automatica',0,0)




def marcar_como_lida(request):
	''' Marcar todas as notificações de um utilizador como lidas '''
	if request.user.is_authenticated:
		user = get_user(request)
	else:
		return redirect('utilizadores:mensagem', 5)
	user.notifications.mark_all_as_read(user)
	return redirect('notificacoes:categorias-notificacao-automatica',0,0)






def sem_notificacoes(request, id):
	''' Página quando não existem notificacoes '''
	if request.user.is_authenticated:
		user = get_user(request)
	else:
		return redirect('utilizadores:mensagem', 5)

	return render(request, 'notificacoes/sem_notificacoes.html', {
		'categoria':id,
	})




def categorias_notificacao_automatica(request, id, nr):
	''' Ver notificações automáticas por categorias '''
	if request.user.is_authenticated:
		user = get_user(request)
	else:
		return redirect('utilizadores:mensagem', 5)
	x = 0   
	if id == 1:
		notificacoes = user.notifications.unread().order_by('-id') 
	elif id ==2:
		notificacoes = user.notifications.read().order_by('-id') 
	elif id == 3:
		notificacoes = Notificacao.objects.filter(recipient_id=user , public=False).order_by('-id')
	elif id ==4:    
		notificacoes = Notificacao.objects.filter(recipient_id=user , public=True).order_by('-id')
	elif id == 5:
		notificacoes = Notificacao.objects.filter(recipient_id=user , level="info").order_by('-id')
	elif id ==6:  
		notificacoes = Notificacao.objects.filter(recipient_id=user , level="warning").order_by('-id')
	elif id ==7: 
		notificacoes = Notificacao.objects.filter(recipient_id=user , level="error").order_by('-id')
	elif id ==8:  
		notificacoes = Notificacao.objects.filter(recipient_id=user , level="success").order_by('-id')
	else:
		notificacoes = user.notifications.all().order_by('-id')
	
	x = len(notificacoes)
	if nr!=0:
		try:
			notificacao = Notificacao.objects.get(id=nr)
		except:  
			if x>0:
				notificacao = notificacoes[0]
			else:
				return redirect("notificacoes:sem-notificacoes", id)      
	else:
		if x>0:
			notificacao = notificacoes[0]
		else:
			return redirect("notificacoes:sem-notificacoes", id)    
	nr_notificacoes_por_pagina = 15
	paginator= Paginator(notificacoes,nr_notificacoes_por_pagina)
	page=request.GET.get('page')
	notificacoes = paginator.get_page(page)
	total = x
	if notificacao != None:
		notificacao.unread = False
		notificacao.save()
	else:
		return redirect("utilizadores:mensagem", 5)
	return render(request, 'notificacoes/detalhes_notificacao_automatica.html', {
		'atual': notificacao, 'notificacoes':notificacoes,'categoria':id,'total':total
	})

class NotificationAddr(Enum):
	INVALIDAR_PROPOSTA = "invalidar_proposta"
	VALIDAR_PROPOSTA = "validar_proposta"
	RECUSAR_INSCRICAO = "recusar_inscricao"
	CANCELAR_INSCRICAO = "cancelar_inscricao"
	RECUSAR_LOGISTICA_LOCATION = "recusar_logisitica_loc"
	ATRIBUIR_LOGISTICA_LOCATION = "atribuir_logistica_loc"
	RECUSAR_LOGISTICA_EQUIP = "recusar_logistica_equip"
	ATRIBUIR_LOGISTICA_EQUIP = "atribuir_logistica_equip"
	RECUSAR_LOGISTICA_SERVICE = "recusar_logistica_service"
	ATRIBUIR_LOGISTICA_SERVICE = "atribuir_logistica_service"


def enviar_notificacao_automatica(request, sigla, id, description=""):
	''' Envio de notificação automatica '''
	if request.user.is_authenticated:
		user_sender = get_user(request)
	elif sigla!="validarRegistosPendentes":
		return redirect('utilizadores:mensagem', 5)

	if sigla == NotificationAddr.CANCELAR_INSCRICAO:
		answer = FormAnswer.objects.get(id=id)
		title = "Inscrição cancelada"
		description = "Inscrição no evento " + answer.event.name + " foi cancelada com sucesso."
		recipient = answer.answerer
		notify.send(sender=get_user(request), recipient=recipient, verb=description, action_object=answer,
			target=None, level="success", description=title, public=False, timestamp=timezone.now())
	# if sigla == NotificationAddr.RECUSAR_INSCRICAO:
	# 	event = Even
	# 	title = "Inscrição cancelada"
	# 	description = "A sua inscrição foi cancelada"
	# 	user_recipient = Generaluser.objects.get(user_ptr=id)
		
	# if sigla == NotificationAddr.INVALIDAR_PROPOSTA:
	# 	desc = "Proposta invalidada"
	# 	verb = "A sua proposta foi "

	if sigla == NotificationAddr.RECUSAR_LOGISTICA_LOCATION:
		loc = Locationuse.objects.get(id=id)
		title = "Logistica localização recusada"
		description = "O seu pedido de logistica foi recusado para o evento" + loc.event.name
		recipient = User.objects.get(id=loc.event.organizer.generaluser_ptr.user_ptr.id)
		notify.send(sender=get_user(request), recipient=recipient, verb=description, action_object=loc,
			target=None, level="warning", description=title, public=False, timestamp=timezone.now())
	elif sigla == NotificationAddr.ATRIBUIR_LOGISTICA_LOCATION:
		loc = Locationuse.objects.get(id=id)
		title = "Logistica localização atribuida"
		description = "O seu pedido de logistica foi aceite para o evento" + loc.event.name
		recipient = User.objects.get(id=loc.event.organizer.generaluser_ptr.user_ptr.id)
		notify.send(sender=get_user(request), recipient=recipient, verb=description, action_object=loc,
			target=None, level="success", description=title, public=False, timestamp=timezone.now())
	if sigla == NotificationAddr.RECUSAR_LOGISTICA_EQUIP:
		item = Itemuse.objects.get(id=id)
		title = "Logistica equipamento recusada"
		description = "O seu pedido de logistica foi recusado para o evento" + item.event.name
		recipient = User.objects.get(id=item.event.organizer.generaluser_ptr.user_ptr.id)
		notify.send(sender=get_user(request), recipient=recipient, verb=description, action_object=item,
			target=None, level="warning", description=title, public=False, timestamp=timezone.now())
	elif sigla == NotificationAddr.ATRIBUIR_LOGISTICA_EQUIP:
		item = Itemuse.objects.get(id=id)
		title = "Logistica equipamento atribuida"
		description = "O seu pedido de logistica foi aceite para o evento" + item.event.name
		recipient = User.objects.get(id=item.event.organizer.generaluser_ptr.user_ptr.id)
		notify.send(sender=get_user(request), recipient=recipient, verb=description, action_object=item,
			target=None, level="success", description=title, public=False, timestamp=timezone.now())
	if sigla == NotificationAddr.RECUSAR_LOGISTICA_SERVICE:
		serv = Serviceuse.objects.get(id=id)
		title = "Logistica serviço recusada"
		description = "O seu pedido de logistica foi recusado para o evento" + serv.event.name
		recipient = User.objects.get(id=serv.event.organizer.generaluser_ptr.user_ptr.id)
		notify.send(sender=get_user(request), recipient=recipient, verb=description, action_object=serv,
			target=None, level="warning", description=title, public=False, timestamp=timezone.now())
	elif sigla == NotificationAddr.ATRIBUIR_LOGISTICA_SERVICE:
		serv = Serviceuse.objects.get(id=id)
		title = "Logistica serviço atribuida"
		description = "O seu pedido de logistica foi aceite para o evento" + serv.event.name
		recipient = User.objects.get(id=serv.event.organizer.generaluser_ptr.user_ptr.id)
		notify.send(sender=get_user(request), recipient=recipient, verb=description, action_object=serv,
			target=None, level="success", description=title, public=False, timestamp=timezone.now())



######################################################### Mensagens #####################################################


# def escolher_tipo(request):
#     ''' Escolher tipo de mensagem a enviar, poderá ser uma mensagem de grupo ou individual '''
#     if request.user.is_authenticated:
#         user = get_user(request)
#     else:
#         return redirect('utilizadores:mensagem', 5)
#     return render(request, 'notificacoes/escolher_tipo_mensagem.html')


# def concluir_envio(request):
#     ''' Página de sucesso quando a mensagem é enviada '''
#     if request.user.is_authenticated:
#         user = get_user(request)
#     else:
#         return redirect('utilizadores:mensagem', 5)

backend/notificacoes/templates/notificacoes/concluir_envio.html
{% extends 'app.html' %}



{% block title %}- Mensagens{% endblock title %}



{% block content %}

<div>


    <div style="padding: 3rem 2vw 1rem;">

        <div class="steps is-success">

            <div class="step-item is-completed is-success">

                <div class="step-marker">

                    <span class="icon">

                        <i class="mdi mdi-account"></i>

                    </span>

                </div>

                <div class="step-details">

                    <p class="step-title">Escolher Tipo</p>

                </div>

            </div>

            <div class="step-item is-completed is-success">

                <div class="step-marker">

                    <span class="icon">

                        <i class="mdi mdi-circle-edit-outline mdi-24px"></i>

                    </span>

                </div>

                

                <div class="step-details">

                    <p class="step-title">Escrever Mensagem</p>

                </div>

            </div>



            <div class="step-item is-completed is-success">

                <div class="step-marker">

                    <span class="icon">

                        <i class="mdi mdi-check"></i>

                    </span>

                </div>

                <div class="step-details">

                    <p class="step-title">Concluir</p>

                </div>

            </div>

        </div>


            <div style="margin-bottom:3%;margin-top:3%;">
                <h2 class="title is-5" style="text-align: center;" >Mensagem enviada com sucesso!</h2>
            </div>
  
    </div>

    <div style="text-align: center;position:center;margin-top:4%">
        <a href="{% url 'notificacoes:detalhes-mensagem' 0 0 %}">
            <button  class="button">Continuar</button>
        </a>
    </div>

    {% endblock content %}

</div>

backend/notificacoes/templates/notificacoes/enviar_notificacao.html
{% extends 'app.html' %}

{% block title %}Enviar Notificação{% endblock title %}

{% block content %}
<div>
    <nav aria-label="breadcrumbs" class="breadcrumb">
        <ul>
            <li><a href="{% url 'home' %}">Início</a></li>
            <li class="is-active"><a>Mensagens</a></li>
        </ul>
    </nav>
    <div style="padding: 3rem 2vw 1rem;">
        <div class="steps is-success">

            <div class="step-item is-completed is-success">

                <div class="step-marker">

                    <span class="icon">

                        <i class="mdi mdi-account"></i>

                    </span>

                </div>

                <div class="step-details">

                    <p class="step-title">Escolher Tipo</p>

                </div>

            </div>

            <div class="step-item is-completed is-success">

                <div class="step-marker">

                    <span class="icon">

                        <i class="mdi mdi-circle-edit-outline mdi-24px"></i>

                    </span>

                </div>



                <div class="step-details">

                    <p class="step-title">Escrever Mensagem</p>

                </div>

            </div>



            <div class="step-item is-success">

                <div class="step-marker">

                    <span class="icon">

                        <i class="mdi mdi-check"></i>

                    </span>

                </div>

                <div class="step-details">

                    <p class="step-title">Concluir</p>

                </div>

            </div>

        </div>
        <div class="columns">
            <div class="column is-3">
            </div>
            <div class="column">
                <div style="padding: 3rem 2vw 1rem;">
                    <form method="post">
                        {% csrf_token %}
                        <div class="field is-horizontal">
                            <div class="field-label is-normal">
                                <label class="label">Destinatário</label>
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <div class="control">
                                        <input class="input" name="email" id="id_email" value="{{form.email.value|default_if_none:"" }}" type="text" placeholder="Insira o email do destinatário">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="field is-horizontal">
                            <div class="field-label is-normal">
                                <label class="label">Título</label>
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <div class="control">
                                        <input class="input" name="titulo" id="id_titulo"
                                            value="{{form.titulo.value|default_if_none:"" }}" type="text"
                                            placeholder="Insira o título da mensagem">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="field is-horizontal">
                            <div class="field-label is-normal">
                                <label class="label">Mensagem</label>
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <div class="control">
                                        <textarea class="textarea" name="mensagem" 
                                            placeholder="Insira a mensagem a enviar">{{form.mensagem.value|default_if_none:"" }}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="field is-horizontal" style="margin-left:22%;margin-top:5%">
                            <div class="field-label">
                                <!-- Left empty for spacing -->
                            </div>
                            <div class="field-body">
                                <div class="field is-grouped">
                                    <p class="control">
                                        <a href="{% url 'notificacoes:enviar-notificacao' %}" class="button is-light">
                                            Voltar
                                        </a>
                                    </p>
                                    <p class="control">
                                        <button style="" type="submit" class="button is-success is-outlined">
                                            <span>Confirmar</span>
                                        </button>
                                    </p>

                                </div>
                            </div>
                        </div>
                        {% if msg %}
                        <div style="margin-top:5%;text-align:center;position:center;">
                            <article class="message is-danger">
                                <div class="message-body">
                                    <p style="text-align: center;">
                                        {% if erro == True %}
                                        
                                        <p style="color: #ff0000; text-align:center">{{msg_erro}}</p>

                                        {% endif %}
                                        {% if form.non_field_errors %}
                                        {% for error in form.non_field_errors %}
                                        <p style="color: #ff0000; text-align:center">{{error}}</p>
                                        {% endfor %}
                                        {% else %}

                                        {% for field in form %}
                                        {% for error in field.errors %}
                                        <p style="color: #ff0000;">{{ error }}</p>
                                        {% endfor %}
                                        {% endfor %}
                                        {%endif%}

                                    </p>
                                </div>
                            </article>
                        </div>
                        {% endif %}
                    </form>

                </div>
            </div>
            <div class="column is-3">
            </div>
        </div>
    </div>
</div>
{% endblock content %}

backend/notificacoes/templates/notificacoes/enviar_para_grupo.html
{% extends 'app.html' %}

{% block title %}Enviar Notificação{% endblock title %}

{% block content %}
<div>
    <nav aria-label="breadcrumbs" class="breadcrumb">
        <ul>
            <li><a href="{% url 'home' %}">Início</a></li>
            <li class="is-active"><a>Mensagens</a></li>
        </ul>
    </nav>
    <div style="padding: 3rem 2vw 1rem;">
        <div class="steps is-success">

            <div class="step-item is-completed is-success">

                <div class="step-marker">

                    <span class="icon">

                        <i class="mdi mdi-account"></i>

                    </span>

                </div>

                <div class="step-details">

                    <p class="step-title">Escolher Tipo</p>

                </div>

            </div>

            <div class="step-item is-completed is-success">

                <div class="step-marker">

                    <span class="icon">

                        <i class="mdi mdi-circle-edit-outline mdi-24px"></i>

                    </span>

                </div>



                <div class="step-details">

                    <p class="step-title">Escrever Mensagem</p>

                </div>

            </div>



            <div class="step-item is-success">

                <div class="step-marker">

                    <span class="icon">

                        <i class="mdi mdi-check"></i>

                    </span>

                </div>

                <div class="step-details">

                    <p class="step-title">Concluir</p>

                </div>

            </div>

        </div>
        <div class="columns">
            <div class="column is-3">
            </div>
            <div class="column">
                <div style="padding: 3rem 2vw 1rem;">
                    <form method="post">
                        {% csrf_token %}
                        <div class="field is-horizontal">
                            <div class="field-label is-normal">
                                <label class="label">Título</label>
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <div class="control">
                                        <input type="text" name="titulo" class="input" id="id_titulo"
                                            value="{{form.titulo.value|default_if_none:"" }}"
                                            placeholder="Insira o título da mensagem">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="field is-horizontal">
                            <div class="field-label is-normal">
                                <label class="label">Mensagem</label>
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <div class="control">
                                        <textarea class="textarea" name="mensagem" 
                                            placeholder="Insira a mensagem a enviar">{{form.mensagem.value|default_if_none:"" }}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="field is-horizontal">
                            <div class="field-label is-normal">
                                <label class="label">Tipo de utilizador</label>
                            </div>
                            <div class="field-body is-expanded">
                                <div class="field">
                                    <div class="control">
                                        <span class="select">
                                            {{form_group.filtro_tipo}}
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>



                        <div class="field is-horizontal" style="margin-left:22%; margin-top:5%">
                            <div class="field-label">
                                <!-- Left empty for spacing -->
                            </div>
                            <div class="field-body">
                                <div class="field is-grouped">
                                    <p class="control">
                                        <a href="{% url 'notificacoes:enviar-notificacao' %}" class="button is-light">
                                            Voltar
                                        </a>
                                    </p>
                                    <button style="" type="submit" class="button is-success is-outlined">
                                        <span>Confirmar</span>
                                    </button>

                                </div>
                            </div>
                        </div>


                    </form>
                    {% if msg %}
                    <div style="margin-top:5%;text-align:center;position:center;">
                        <article class="message is-danger">
                            <div class="message-body">
                                <p style="text-align: center;">

                                    {% if form.non_field_errors %}
                                    {% for error in form.non_field_errors %}
                                    <p style="color: #ff0000; text-align:center">{{error}}</p>
                                    {% endfor %}
                                    {% else %}

                                    {% for field in form %}
                                    {% for error in field.errors %}
                                    <p style="color: #ff0000;">{{ error }}</p>
                                    {% endfor %}
                                    {% endfor %}
                                    {%endif%}

                                </p>
                            </div>
                        </article>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="column is-3">
            </div>
        </div>
    </div>
</div>
{% endblock content %}