backend/Event_Management/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
import notifications.urls
from django.conf.urls.static import static

urlpatterns = [
	path('forms/', include('forms.urls')),
	path('resources/', include('resources.urls')),
	path('pre_events/', include('pre_events.urls')),
	path('events/', include('events.urls')),
	path('users/', include('users.urls')),
	path('admin/', admin.site.urls),
	path('notificacoes/', include('notificacoes.urls')),
	path('', include('main.urls')),
    path('', include("notifications.urls", namespace='notifications')),

]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

backend/pre_events/urls.py
from django.urls import path
from django.conf.urls import url, include

from .views import *

urlpatterns = [
	path('consult_events/', consult_events, name='consult_events'),
	path('proponent_events/', proponent_events, name='proponent_events'),
	path('admin_events/', admin_events, name='admin_events'),
	path('delete_event/<int:id>', delete_event, name='delete_event'),
	path('event_details/<int:id>', event_details, name='event_details'),
	path('event_logistics_form/<int:id>', event_logistics_form, name='event_logistics_form'),
	path('view_event_logistic/<int:id>', view_event_logistic, name='view_event_logistic'),
	path('delete_event_logistic/<int:id>', delete_event_logistic, name='delete_event_logistic'),
	path('attrib_equipment/<int:id>', attrib_equipment, name='attrib_equipment'),
	path('attrib_service/<int:id>', attrib_service, name='attrib_service'),
	path('attrib_location/<int:id>', attrib_location, name='attrib_location'),
	path('event_logistic_list/<int:id>', event_logistic_list, name='event_logistic_list'),
	path('change_logistic_equipment/<int:id>', change_logistic_equipment, name='change_logistic_equipment'),
	path('change_logistic_location/<int:id>', change_logistic_location, name='change_logistic_location'),
	path('change_logistic_service/<int:id>', change_logistic_service, name='change_logistic_service'),
	path('create_event/', create_event, name='create_event'),
	path('delete_service/<int:id>/<int:num>', delete_service, name='delete_service'),
	path('delete_equipment/<int:id>/<int:num>', delete_equipment, name='delete_equipment'),
	path('delete_location/<int:id>/<int:num>', delete_location, name='delete_location'),
	path('validate_equipment/<int:id>', validate_equipment, name='validate_equipment'),
	path('validate_service/<int:id>', validate_service, name='validate_service'),
	path('validate_location/<int:id>', validate_location, name='validate_location'),
	path('invalidate_equipment/<int:id>', invalidate_equipment, name='invalidate_equipment'),
	path('invalidate_service/<int:id>', invalidate_service, name='invalidate_service'),
	path('invalidate_location/<int:id>', invalidate_location, name='invalidate_location'),
	path('delete_attrib_location/<int:id>', delete_attrib_location, name='delete_attrib_location'),
	path('delete_attrib_equipment/<int:id>', delete_attrib_equipment, name='delete_attrib_equipment'),
	path('delete_attrib_service/<int:id>', delete_attrib_service, name='delete_attrib_service'),
	path('validate_logistics/<int:id>', validate_logistics, name="validate_logistics"),
	path('end_events/<int:id>', end_event, name="end_event")
]

backend/pre_events/models.py
from django.db import models

# Create your models here.

backend/pre_events/forms.py
from django import forms
from django.forms.models import modelformset_factory

from resources.models import Event, Eventtype, Requestequipment, Requestlocation, Requestservices, Itemuse, Serviceuse, Locationuse


resource_groups = [
	("services", "Tipos de serviço"),
	("equipment", "Tipos de equipamento"),
	("location" , "Tipos de espaço")
]

groups = Eventtype.objects.all()

eventtype_dict = {}

for group in groups:
	key = str(group.pk)
	value = str(group.name)
	eventtype_dict[key] = value

eventtype_choices = [(k, v) for k, v in eventtype_dict.items()]

class EventLogisticsForm(forms.Form):
	resource_type = forms.CharField(label="Selecione o recurso que pretende adicionar",
									widget=forms.Select(choices=resource_groups))

class EventForm(forms.ModelForm):
	class Meta:
		model = Event
		fields = ["name", "description", "eventtype", "start", "end", "state"]
		excluded = ('state',)
		widgets = {
			"name" : forms.TextInput(attrs={ 'class':'input' }),
			"description": forms.Textarea(attrs={ 'class':'textarea' }),
			"eventtype": forms.Select(choices=eventtype_choices),
			"start": forms.DateTimeInput(attrs={ 'class':'input', 'type':'datetime-local' }),
			"end": forms.DateTimeInput(attrs={ 'class':'input', 'type':'datetime-local' }),
			"state": forms.HiddenInput(attrs={'value':'0'})
		}

class RequestEquipmentForm(forms.ModelForm):
	class Meta:
		model = Requestequipment
		fields = ["typeequipment", "start", "end", "quantity"]
		widgets = {
			"typeequipment" : forms.Select(attrs={
				'class': 'select is-info',
			}),
            "start" : forms.DateTimeInput(attrs={
				'class': 'input',
				'type': 'datetime-local'
			}),
            "end" : forms.DateTimeInput(attrs={
				'class': 'input',
				'type': 'datetime-local'
			}),
			"quantity" : forms.NumberInput(attrs={
				"class": "input",
               "min":"1",
               "max":"99"
            }),
		}

class RequestLocationForm(forms.ModelForm):
	class Meta:
		model = Requestlocation
		fields = ["locationtype", "start", "end", "quantity"]
		widgets = {
			"locationtype" : forms.Select(attrs={
				'class': 'select is-info',
			}),
            "start" : forms.DateTimeInput(attrs={
				'class': 'input',
				'type': 'datetime-local'
			}),
            "end" : forms.DateTimeInput(attrs={
				'class': 'input',
				'type': 'datetime-local'
			}),
			"quantity" : forms.NumberInput(attrs={
				"class": "input",
           		"min":"1",
            	"max":"99"
            }),
		}

class RequestServicesForm(forms.ModelForm):
	class Meta:
		model = Requestservices
		fields = ["servicestype", "start", "end", "quantity"]
		widgets = {
			"servicestype" : forms.Select(attrs={
				'class': 'select is-info',
			}),
            "start" : forms.DateTimeInput(attrs={
				'class': 'input',
				'type': 'datetime-local'
			}),
            "end" : forms.DateTimeInput(attrs={
				'class': 'input',
				'type': 'datetime-local'
			}),
            "quantity" : forms.NumberInput(attrs={
				"class": "input",
               	"min":"1",
               	"max":"99"
            }),
		}

class ItemuseForm(forms.ModelForm):
    # specify the name of model to use
    class Meta:
        model = Itemuse
        fields = ["start", "end"]
        widgets = {
            "start" : forms.DateTimeInput(attrs={
				'class': 'input',
				'type': 'datetime-local'
			}),
            "end" : forms.DateTimeInput(attrs={
				'class': 'input',
				'type': 'datetime-local'
			}),
        }

class ServiceuseForm(forms.ModelForm):
    # specify the name of model to use
    class Meta:
        model = Serviceuse
        fields = ["start", "end"]
        widgets = {
            "start" : forms.DateTimeInput(attrs={
				'class': 'input',
				'type': 'datetime-local'
			}),
            "end" : forms.DateTimeInput(attrs={
				'class': 'input',
				'type': 'datetime-local'
			}),
		}

class LocationuseForm(forms.ModelForm):
    # specify the name of model to use
    class Meta:
        model = Locationuse
        fields = ["start", "end"]
        widgets = {
            "start" : forms.DateTimeInput(attrs={
				'class': 'input',
				'type': 'datetime-local'
			}),
            "end" : forms.DateTimeInput(attrs={
				'class': 'input',
				'type': 'datetime-local'
			}),
		}

RequestServicesFormset = modelformset_factory(model=Requestservices, form=RequestServicesForm, fields=("servicestype", "start", "end", "quantity"), can_delete=True)
RequestEquipmentFormset = modelformset_factory(model=Requestequipment, form=RequestEquipmentForm, fields=("typeequipment", "start", "end", "quantity"), can_delete=True)
RequestLocationFormset = modelformset_factory(model=Requestlocation, form=RequestLocationForm, fields=("locationtype", "start", "end", "quantity"), can_delete=True)

backend/pre_events/templates/admin_events.html
{% extends 'app.html' %}

{% block title %}- Consultar Inscrições{% endblock title %}

{% block content %}

<div>
	<div style="margin-bottom:3%;margin-top:3%">
		<h2 class="title is-4"style="text-align: center"> Consulta de eventos </h2>
	</div>
	<table id="example" class="table is-fullwidth">
		<thead>
			<tr>
				<th><strong> Nome </strong> </th>
				<th><strong> Descrição </strong> </th>
				<th><strong> Estado </strong> </th>
				<th><strong> Início </strong> </th>
				<th><strong> Fim </strong> </th>
				<th><strong> Tipo de evento </strong> </th>
				<th><strong> Organizador </strong> </th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{% for event in events  %}
				<tr>
					<td style="font-weight: normal"> {{ event.name }}</td>
					<td style="font-weight: normal"> {{ event.description }}</td>
					{% if event.state == 0 %}
						<td style="font-weight: normal"> Pendente </td>
					{% else %}
						<td style="font-weight: normal"> Validado </td>
					{% endif %}
					<td style="font-weight: normal"> {{ event.start }}</td>
					<td style="font-weight: normal"> {{ event.end }}</td>
					<td style="font-weight: normal"> {{ event.eventtype.name }}</td>
					<td style="font-weight: normal"> {{ event.organizer.generaluser_ptr.user_ptr.username }}</td>
					<td style="text-align: right"> <a class="btn-primary" href="{% url 'event_details' event.id %}"> <span>Detalhes</span> </a> </td>
					<td style="text-align: right"> <a class="btn-primary" href="{% url 'delete_event' event.id %}" onclick="return confirm('Tem a certeza?');"> <span>Eliminar</span> </a> </td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

<script>
 $(document).ready(function () {
    $('#example').DataTable({
      "language": {
        "url": "//cdn.datatables.net/plug-ins/1.10.24/i18n/Portuguese.json"
      }
    });
  });
</script>

{% endblock content %}

{% block scripts %}
<script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/dataTables.bulma.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bulma-accordion@2.0.1/dist/js/bulma-accordion.min.js"></script>
{% endblock scripts %}

backend/pre_events/templates/change_event_logistic.html
{% extends 'app.html' %}

{% block title %}- Detalhes do Evento{% endblock title %}

{% block content %}
{% load static %}

<div>
	<div style="margin-bottom:3%;margin-top:3%">
        <h2 class="title is-4" style="text-align: center"> Alterar logística de um {{ name }} </h2>
	</div>

	<div style="display:block;text-align:center">
		<form method="POST" style="display:inline-block; margin-left:auto; margin-right:auto; text-align:left">
			{% csrf_token %}
			{% for field in form %}
				<div class="columns">
					<div class="column">  
						<div class="field is-grouped">
							<label class="label">{{ field.label_tag }}</label>
							<div class="control">
								{{field}}
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
			<div style="margin-top:7%;text-align: center;position:center;">
				<button type="submit" class="button is-success is-outlined" onclick="return confirm('Tem a certeza?');">
					<span>Confirmar</span>
				</button>
			</div>
		</form>
	</div>
</div>

<script>
	$(document).ready(function () {
		$("#{{id_name}} > option").each(function(){
			if({{selected_id}} == this.value){
				$(this).attr("selected", "selected");
				console.log(this.text + ' ' + this.value);
			}
			else{
				$(this).removeAttr("selected");
			}
		})
		$(".control").find(".select").each(function(){
			$(this).parent().addClass("select is-info");
		})
	});
</script>

{% endblock content %}

backend/pre_events/templates/consult_events.html
{% extends 'app.html' %}

{% block title %}- Consultar Inscrições{% endblock title %}

{% block content %}

{% load main_extras %}

<div>
    <div style="margin-bottom:3%;margin-top:3%">
        <h2 class="title is-4"style="text-align: center"> Consulta de eventos </h2>
    </div>
    <table id="example" class="table is-fullwidth">
        <thead>
            <tr>
                <th><strong> Nome </strong> </th>
                <th><strong> Descrição </strong> </th>
                <th><strong> Estado </strong> </th>
                <th><strong> Início </strong> </th>
                <th><strong> Fim </strong> </th>
                <th><strong> Tipo de evento </strong> </th>
                <th><strong> Organizador </strong> </th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{% for event in events  %}
				<tr>
					<td style="font-weight: normal"> {{ event.name }}</td>
					<td style="font-weight: normal"> {{ event.description }}</td>
					{% if event.state == 0 %}
						<td style="font-weight: normal"> Pendente </td>
					{% else %}
						<td style="font-weight: normal"> Validado </td>
					{% endif %}
					<td style="font-weight: normal"> {{ event.start }}</td>
					<td style="font-weight: normal"> {{ event.end }}</td>
					<td style="font-weight: normal"> {{ event.eventtype.name }}</td>
					<td style="font-weight: normal"> {{ event.organizer.generaluser_ptr.user_ptr.username }}</td>
					{% if event.formsignupid %}
						{% if event in registered %}
							<td style="text-align: right; color: gray"> <b class="btn-primary"> <span>Inscrever</span> </b> </td>
						{% else %}
							<td style="text-align: right"> <a class="btn-primary" href="/forms/respond/{{event.formsignupid.id}}/?event={{event.id}}"> <span>Inscrever</span> </a> </td>
						{% endif %}
					{% else %}
						<td> </td>
					{% endif %}
					<td style="text-align: right"> <a class="btn-primary" href="{% url 'event_details' event.id %}"> <span>Detalhes</span> </a> </td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

<script>
 $(document).ready(function () {
    $('#example').DataTable({
      "language": {
        "url": "//cdn.datatables.net/plug-ins/1.10.24/i18n/Portuguese.json"
      }
    });
  });
</script>

{% endblock content %}


{% block scripts %}
<script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/dataTables.bulma.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bulma-accordion@2.0.1/dist/js/bulma-accordion.min.js"></script>
{% endblock scripts %}

backend/pre_events/templates/create_event.html
{% extends 'app.html' %}

{% block title %}- Consultar Eventos{% endblock title %}

{% block content %}

{% load main_extras %}

<div>
	<div style="margin-bottom:3%;margin-top:3%;">
		<h2 class="title is-4" style="text-align: center;">Criar novo evento</h2>
	</div>

	<div style="display:block;text-align:center">
		<form method="POST" style="display:inline-block; margin-left:auto; margin-right:auto; text-align:left">
			{% csrf_token %}
			{% for field in form.visible_fields %}
				<div class="columns">
					<div class="column">  
						<div class="field is-grouped">
							<label class="label">{{ field.label_tag }}</label>
							<div class="control">
								{{field}}
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
			{% for field in form.hidden_fields %}
				{{field}}
			{% endfor %}
			<div style="margin-top:7%;text-align: center;position:center;">
				<button type="submit" class="button is-success is-outlined" onclick="return confirm('Tem a certeza?');">
					<span>Submeter</span>
				</button>
			</div>
		</form>

	</div>
</div>

{% endblock content %}

backend/pre_events/templates/event_details.html
{% extends 'app.html' %}

{% block title %}- Detalhes do Evento{% endblock title %}

{% block content %}

{% load main_extras %}

<style>
	h4 {
		font-weight: normal
	}
</style>
<div>
	<div style="margin-bottom:3%;margin-top:3%">
        <h2 class="title is-4" style="text-align: center"> Detalhes do evento:  {{ event.name }} </h2>
	</div>
	<div class="columns">
		<div class="column">
			<h4><strong>Nome: </strong>{{ event.name }}</h4>
			<h4><strong>Descrição: </strong>{{ event.description }}</h4>
			<h4><strong>Data de início: </strong>{{ event.start }}</h4>
			<h4><strong>Data de fim: </strong>{{ event.end }}</h4>
			<h4><strong>Tipo de evento: </strong>{{ event.eventtype.name }}</h4>
			{% if event.state == 0 %}
				<h4><strong>Estado: </strong>Aguardando preenchimento do formulário do evento</h4>
			{% elif event.state == 1 %}
				<h4><strong>Estado: </strong>Aguardando validação do formulário do evento</h4>
			{% elif event.state == 2 %}
				<h4><strong>Estado: </strong>Aguardando criação do formulário do evento</h4>
			{% elif event.state == 3 %}
				<h4><strong>Estado: </strong>Aguardando validação da logística do evento</h4>
			{% elif event.state == 4 %}
				<h4><strong>Estado: </strong>Logística do evento validada</h4>
			{% else %}
				<h4><strong>Estado: </strong>Evento acabou. Pode submeter feedback.</h4>
			{% endif %}
		</div>
		<div class="column">
			{% if event.state == 0 %}
				{% if request.user|has_group:'proponent' %}
					<a href="/forms/respond/{{form.id}}/?event={{event.id}}" class="button is-info is-outlined" style="display:block;margin: 0 auto ">
						<span>Preencher formulário do evento</span>
					</a>
				{% endif %}
			{% elif event.state == 1 %}
				{% if request.user|has_group:'proponent' or request.user|has_group:'administrator' %}
					<a href="/forms/validate/{{form.id}}/?event={{event.id}}" class="button is-info is-outlined" style="display:block;margin: 0 auto ">
						<span>Validar formulário do evento</span>
					</a>
				{% endif %}

				{% if request.user|has_group:'proponent' %}
					<a href="/forms/edit_response/{{proposal.id}}/?event={{event.id}}" class="button is-info is-outlined" style="display:block;margin: 0 auto ">
						<span>Editar formulário do evento</span>
					</a>
				{% endif %}
			{% elif event.state == 2 %}
				{% if request.user|has_group:'proponent' %}
					<a href="{% url 'event_logistics_form' event.id %}" class="button is-info is-outlined" style="display:block;margin: 0 auto ">
						<span>Criar logística do evento</span>
					</a>
				{% endif %}
			{% elif event.state == 3 %}
				{% if request.user|has_group:'proponent' or request.user|has_group:'administrator' %}
					<a href="{% url 'view_event_logistic' event.id %}" class="button is-info is-outlined" style="display:block;margin: 0 auto ">
						<span>Ver logística do evento</span>
					</a>
				{% endif %}
			{% elif event.state == 4 %}
				{% if request.user|has_group:'participant' %}
					<a href="/forms/respond/{{event.formsignupid.id}}/?event={{event.id}}" class="button is-info is-outlined" style="display:block;margin: 0 auto ">
						<span>Inscrever-me</span>
					</a>
				{% endif %}
			{% else %}
				{% if request.user|has_group:'participant' %}
					<a href="/forms/respond/{{event.formfeedbackid.id}}/?event={{event.id}}" class="button is-info is-outlined" style="display:block;margin: 0 auto ">
						<span>Fornecer feedback</span>
					</a>
				{% endif %}
			{% endif %}
				{% if request.user|has_group:'proponent' or request.user|has_group:'administrator' %}
					<a href="/forms/responses/{{event.formsignupid.id}}/?event={{event.id}}" class="button is-info is-outlined" style="display:block;margin: 0 auto ">
						<span>Participantes</span>
					</a>
					<a href="{% url 'end_event' event.id %}" class="button is-danger is-outlined" style="display:block;margin: 0 auto ">
						<span>Terminar evento</span>
					</a>
					<a href="/forms/responses/{{event.formfeedbackid.id}}/?event={{event.id}}" class="button is-info is-outlined" style="display:block;margin: 0 auto ">
						<span>Consultar feedback</span>
					</a>
				{% endif %}
		</div>
	</div>

</div>
{% endblock content %}

backend/pre_events/templates/logistics_form.html
{% extends 'app.html' %}

{% block title %}- Detalhes do Evento{% endblock title %}

{% block content %}
{% load static %}

{% load main_extras %}

<div>
	<div style="margin-bottom:3%;margin-top:3%">
		  <h2 class="title is-4" style="text-align: center"> Criar/Adicionar logística do evento </h2>
	</div>
	<div style="display:block;text-align:center">
		<div style="margin-bottom:2%" class="logistics-add">
			<button id="add-service" class="button is-info" onclick="addForm(event)">Adicionar serviço</button>
			<button id="add-equipment" class="button is-info" onclick="addForm(event)">Adicionar equipamento</button>
			<button id="add-location" class="button is-info" onclick="addForm(event)">Adicionar localização</button>
		</div>

		<form id="form-container" method="POST" style="display:inline-block; margin-left:auto; margin-right:auto; text-align:left">
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th>Logistic type</th>
						<th>Start</th>
						<th>End</th>
						<th>Quantity</th>
					</tr>
				</thead>
				<tbody>
					{% csrf_token %}
					<div id="services-form-count">
						{{ servicesformset.management_form }}
					</div>
					{% for form in servicesformset %}
					<tr class="service-form">
						<td>Serviço</td>
						<td>
							<div class="select">
								{{ form.servicestype }}
							</div>
						</td>
						<td>{{ form.start }}</td>
						<td>{{ form.end }}</td>
						<td>{{ form.quantity }}</td>
					</tr>
					{% endfor %}
				
					<div id="equips-form-count">
						{{ equipsformset.management_form }}
					</div>
					{% for form in equipsformset %}
					<tr class="equipment-form">
						<td>Equipamento</td>
						<td>
							<div class="select">
								{{ form.typeequipment }}
							</div>
						</td>
						<td>{{ form.start }}</td>
						<td>{{ form.end }}</td>
						<td>{{ form.quantity }}</td>
					</tr>
					{% endfor %}
				
					<div id="locations-form-count">
						{{ locationsformset.management_form }}
					</div>
					{% for form in locationsformset %}
					<tr class="location-form">
						<td>Localização</td>
						<td>
							<div class="select">
								{{ form.locationtype }}
							</div>
						</td>
						<td>{{ form.start }}</td>
						<td>{{ form.end }}</td>
						<td>{{ form.quantity }}</td>
					</tr>
					{% endfor %} 
				</tbody>
			</table>

			

			<div class="submit-button" style="margin-top:7%;text-align: center;position:center;">
				<button type="submit" class="button is-success" onclick="return confirm('Tem a certeza?');">
					<span>Submeter</span>
				</button>
			</div>
		</form>
	</div>
</div>

<script>

	let serviceForms = document.querySelectorAll(".service-form");
	let equipmentForms = document.querySelectorAll(".equipment-form");
	let locationForms = document.querySelectorAll(".location-form");

	let addService = document.querySelector("#add-service");
	let addEquipment = document.querySelector("#add-equipment");
	let addLocation = document.querySelector("#add-location");
	
	let servicesTotalForms = document.getElementById("services-form-count").querySelector("#services-TOTAL_FORMS").value;
	let equipsTotalForms = document.getElementById("equips-form-count").querySelector("#equips-TOTAL_FORMS").value;
	let locationsTotalForms = document.getElementById("locations-form-count").querySelector("#locations-TOTAL_FORMS").value;

	function addForm(e) {
		e.preventDefault();
		let formRegex = RegExp(`form-(\\d){1}-`,'g');
	
		switch(e.target.id) {
			case 'add-service':
				var temp = $(".service-form").first();
				var txt = temp.html();
				var newForm = temp.clone().appendTo(".table");

				++servicesTotalForms;
				newForm.html(txt.replace(formRegex, `form-${servicesTotalForms}-`));
				break;
			case 'add-equipment':
				var temp = $(".equipment-form").first();
				var txt = temp.html();
				var newForm = temp.clone().appendTo(".table");

				equipsTotalForms++;
				newForm.html(txt.replace(formRegex, `form-${equipsTotalForms}-`));
				break;
			case 'add-location':
				var temp = $(".location-form").first();
				var txt = temp.html();
				var newForm = temp.clone().appendTo(".table");

				locationsTotalForms++;
				newForm.html(txt.replace(formRegex, `form-${locationsTotalForms}-`));
				break;
			default:
				console.log("Something went wrong.");
		}
	}

	

	{% comment %} legacy code, felt bad deleting it after spending so much time on it{% endcomment %}

	{% comment %} $(document).ready(function() {

		let id = 0;
		$(".query-db").click(function(e) {
			e.preventDefault();
			var type_resource = $('#id_resource_type').val();
			if(type_resource === 'services') {
				$.getJSON("{% url 'get_services' %}", function(services) {
					let array = JSON.parse(services);
					if(!$('input[name="service"]').length) {
						$('.inject-fields').append('<label>Selecione um serviço da lista: </label>');
						array.forEach(function(service) {
							$('.inject-fields').append(`<div class="field is-grouped"><label class="checkbox"><input type="checkbox" name="service" id=${service.fields.name} value=${service.pk} >&nbsp;&nbsp;${service.fields.name}</label>&nbsp;&nbsp;<label class="quantity" hidden>Quantity: <input name="quantity-service" type="number" min="1" max="20" value="1" /></label><br/></div>`);
						});
					}
				});
			}
			else if(type_resource === 'equipment') {
				$.getJSON("{% url 'get_equipments' %}", function(equipments) {
					let array = JSON.parse(equipments);
					if(!$('input[name="equipment"]').length) {
						$('.inject-fields').append('<label>Selecione um equipamento da lista: </label>');
						array.forEach(function(element, index) {
							$('.inject-fields').append(`<div class="field is-grouped"><label class="checkbox"><input type="checkbox" name="equipment" id=${element.fields.name} value=${element.pk} >&nbsp;&nbsp;${element.fields.name}</label>&nbsp;&nbsp;<label class="quantity" hidden>Quantity: <input name="quantity-equipment" type="number" min="1" max="20" value="1" /></label><br/></div>`);
						});
					}
				});
			}
			else if(type_resource === 'location') {
				$.getJSON("{% url 'get_locations' %}", function(locations) {
					let array = JSON.parse(locations);
					if(!$('input[name="location"]').length) {
						$('.inject-fields').append('<label>Selecione um espaço da lista: </label>');
						array.forEach(function(location) {
							$('.inject-fields').append(`<div class="field is-grouped"><label class="checkbox"><input type="checkbox" name="location" id=${location.fields.name} value=${location.pk} >&nbsp;&nbsp;${location.fields.name}</label>&nbsp;&nbsp;<label class="quantity" hidden>Quantity: <input name="quantity-location" type="number" min="1" max="20" value="1" /></label><br/></div>`);
						});
					}
				});
			}
		});

		$('.inject-fields').on('click', "input[type=checkbox]", function() {
			if($(this).is(':checked'))
				$(this).parent().parent().find('.quantity').toggle();
			else
				$(this).parent().parent().find(".quantity").toggle();
		});
	}) {% endcomment %}



</script>
{% endblock content %}